swagger: "2.0"
info:
  title: ProjectAgora
  description: >-
    Optional multiline or single-line description in
    [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.0.1
host: 127.0.0.1:8080
basePath: /v1
schemes: 
  - https
consumes: 
  - application/json
produces: 
  - application/json
securityDefinitions:
  APIKeyHeader: 
    type: apiKey
    in: header
    name: api_key
security:
  - APIKeyHeader: []
definitions:
  Error:
    description: 错误
    properties:
      code: 
        type: integer
        example: 401
      message: 
        type: string    
  TokenStatus:
    description: Token信息
    properties:
      learnerID:
        type: string
      token:
        type: string
      expireBy:
        type: string
      refreshed:
        type: boolean
  LoginRequest:
    description: 登陆请求
    properties:
      username:
        type: string
      password:
        type: string
  Learner:
    description: 学习者
    properties:
      id:
        description: ID
        type: integer
      givenName:
        description: 名
        type: string
      familyName:
        description: 姓
        type: string
      nickname:
        description: 昵称
        type: string
      isMentor:
        description: 是否导师
        type: boolean
      gender:
        description: 性别
        type: string
      ethnicity:
        description: 民族
        type: string  
      birthday:
        description: 生日
        type: string  
      age:
        description: 年龄（应当是计算字段）
        type: number
      status:
        description: 目前状态，包括在读、在读（游学）、在读（试读）、毕业、导师等；考虑是否需要更换成integer
        type: string
      mainPersonalIdType:
        description: 证件类型
        type: string
      mainPersonalId:
        description: 证件号码
        type: string
      dateOfRegistration:
        description: 加入时间
        type: string
      reasonOfRegistration:
        description: 加入原因
        type: string
      previousStatus:
        description: 加入前状态
        type: string
      dateOfLeave:
        description: 离开时间
        type: string
      reasonOfLeave:
        description: 离开原因
        type: string
      destinationOfLeave:
        description: 下阶段目的地
        type: string
      mentorship:
        description: 导师关系
        type: array
        items:
          type: object
          properties:
            mentorType:
              description: 导师类型,  分有负责导师mentorResponsible,协同导师mentorSupportive, 家校沟通导师mentorCommunicative)
              type: string
            mentorID:
              description: 导师ID
              type: integer
            mentorName:
              description: 导师名称
              type: string
      salaryCard:
        description: 工资卡号
        type: string
      custodianInfo:
        description: 监护人信息
        type: array
        items:
          type: object
          properties: 
            name:
              description: 姓名
              type: string
            relationship:
              description: 关系 
              type: string
      emergentContact:
        description: 紧急联系人
        type: array
        items:
          type: object
          properties:
            name: 
              description: 紧急联系人姓名
              type: string
            number:
              description: 紧急联系人电话
              type: string
      contactInfo:
        description: 联系信息
        type: object
        properties:
          phoneNumber:
            description: 电话号码
            type: string
          weChat:
            description: 微信
            type: string
          QQ:
            description: QQ
            type: string
          mailAddress:
            description: 收件地址（用以寄送书面文件）
            type: string
          email:
            description: 电子邮箱
            type: string
      medicalInfo:
        description: 医疗记录
        type: object
        properties:
          generalHealthStatus:
            description: 整体健康状况；0 - 很好（基本不生病，从不住院）； 1 - 一般（偶尔生病住院）； 2 - 欠佳（每个季度都曾生病住院）
            type: integer
            enum: [0, 1, 2]
          bloodType:
            description: 血型
            type: string
          lastPhysicalExam:
            description: 最近一次体检时间(以年为单位)
            type: number
          previousDiagnosis:
            description: 既往疾病
            type: array
            items:
              type: object
              properties: 
                nameOfDiagnosis:
                  description: 疾病名称
                  type: string
                hospitalOfDiagnosis:
                  description: 诊断医院
                  type: string
          regularMedication:
            description: 长期用药
            type: array
            items:
              type: object
              properties:
                nameOfMedication:
                  description: 药品名
                  type: string
                instructionOfMedication:
                  description: 用药医嘱
                  type: string
          foodAlergy:
            description: 食物过敏
            type: object
            properties:
              lactoseIntolerance: 
                description: 奶类过敏（乳糖不耐受）
                type: boolean
              eggAllergy:
                description: 禽蛋类过敏
                type: boolean
              fishAllergy:
                description: 鱼类过敏
                type: boolean
              shellAllergy:
                description: 甲壳类（虾蟹、贝类水产等）
                type: boolean
              peanutAllergy:
                description: 花生过敏
                type: boolean
              soyBeanAllergy:
                description: 大豆过敏
                type: boolean
              nutAllergy:
                description: 坚果类过敏
                type: boolean
              wheatAllergy:
                description: 小麦过敏
                type: boolean
              otherFoodAllergy:
                description: 其他食物过敏
                type: array
                items:
                  type: string
          medicationAllergy:
            description: 药物过敏
            type: object
            properties:
              antibioticsAllergy:
                description: 抗生素过敏（青霉素、氨基苄青霉素、链霉素、卡那霉素）
                type: boolean
              sulfonamidesAllergy:
                description: 磺胺类药物过敏（磺胺噻唑、磺胺嘧啶、长效磺胺、复方新诺明等）
                type: boolean
              painkillerAllergy:
                description: 解热镇痛药（阿司匹林、去痛片）
                type: boolean
              anestheticAllergy:
                description: 麻醉用药（普鲁卡因）
                type: boolean
              vaccineAllergy:
                description: 疫苗类药物
                type: boolean
              otherMedicationAllergy:
                description: 其他药物过敏
                type: array
                items:
                  type: string
      notes:
        description: 备注
        type: array
        items: 
          type: string
    required:
      - name
      - isMentor
  Project:
    description: 项目
    properties:
      id:
        description: 项目ID
        type: integer
      name: 
        description: 项目名称
        type: string
      createdTime:
        description: 创建时间
        type: string
      createdByID:
        description: 创建人ID
        type: integer
      createdBy:
        description: 创建人（姓名）
        type: string
      relatedCourseId:
        description: 关联的课程ID；自由项目的课程ID为0
        type: integer
      relatedCourse:
        description: 关联的课程
        type: string
      projectTerm:
          description: 项目开始学期
          type: string
      projectTermLength:
        description: 持续时间（以学期为单位）
        type: integer
      projectStartDate:
        description: 项目开始时间
        type: string
      averageIntendedCreditHourPerWeek:
        description: 预期周均学时
        type: integer
      totalIntendedCreditHour:
        description: 预期总学时
        type: integer
      projectMentorID:
        description: 项目导师ID
        type: integer
      projectMentor:
        description: 项目导师
        type: string
      averageGuidingHourPerWeek:
        description: 导师周均指导时间
        type: integer
      projectMeta: 
        description: 项目元信息
        type: object
        properties:
          projectIntro:
            description: 项目简介
            type: string
          projectGoal:
            description: 项目目标
            type: string
          evaluationSchema:
            description: 项目评价标准
            type: string
          projectPlan:
            description: 项目计划
            type: string
          instructionPlan: 
            description: 项目指导规划
            type: string
      projectApprovalInfo:
        description: 项目审核信息
        type: object
        properties:
          ApprovalCommitteeOfAcademics:
            description: 学术委员会审核
            type: object
            properties:
              result: 
                description: 学术委员会审核结果
                type: string
              advice:
                description: 学术委员会审核建议
                type: string
          ApprovalMentor:
            description: 导师审核
            type: object
            properties:
              result:
                description: 导师审核结果
                type: string
              advice: 
                description: 导师审核建议
                type: string
      content: 
        description: 项目记录的条目
        type: array
        items: 
          type: object
          properties:
            itemTitle:
              description: 条目标题
              type: string
            itemStartDate:
              description: 条目开始时间; 若存在关联课程，该条为空
              type: string  
            itemEndDate:
              description: 条目结束时间; 若存在关联课程，该条为空
              type: string
            itemContent:
              description: 条目内容；若存在关联课程，该条为空
              type: string
            itemRecord:
              description: 条目记录
              type: string
            itemComment:
              description: 条目评语
              type: string
      conclusionInfo:
        description: 项目结项信息
        type: object
        properties:
          selfEvaluation: 
            description: 项目负责人结项自评
            type: string
          MentorEvaluation:
            description: 导师结项评语
            type: string
    required:
      - name
      - createdTime
      - createdBy
      - relatedCourseId
  Course:
    description: 课程
    properties:
      id:
        description: 课程ID
        type: integer
      name:
        description: 课程名称
        type: string
      createdTime: 
        description: 创建时间 
        type: string
      createdByID:
        description: 创建人
        type: integer  
      createdBy:
        description: 创建人
        type: integer
      creditHour:
        description: 学时设置
        type: number
      courseTimeShift:
        description: 上课时间
        type: string
      courseLengthInWeeks:
        description: 上课周数
        type: integer
      formAndEvaluation:
        description: 课程形式与评价方式
        type: string
      goalOfcourse:
        description: 课程目的
        type: string
      objectivesOfInstruction:
        description: 教学目标
        type: string
      planOfInstruction:
        description: 教学安排
        type: string
      miscellaneousNote:
        description: 其他注意事项
        type: string
      instructions:
        description: 课程引导内容
        type: array
        items:
            type: object
            properties:
              instructionTitle:
                description: 引导条目标题
                type: string
              instructionStartDate:
                description: 引导条目开始时间
                type: string  
              instructionEndDate:
                description: 引导条目结束时间
                type: string
              instructionContent:
                description: 引导条目内容
                type: string
  CreditHourEntry:
    description: 学时授予记录
    properties:
      value: 
        description: 学时授予值(按分钟记)
        type: number
      grantTo: 
        description: 学时获得者ID
        type: integer
      grantBy: 
        description: 学时申请者ID(若是课程学时则为课程导师申请)
        type: integer
      grantFor:
        description: 学时相关项目ID(若无相关项目，则为0)
        type: integer
      grantNote:
        description: 学时授予备注
        type: string
      grade:
        description: 学时相关绩点（若不属于绩点学时，则为-1）
        type: integer
      applicationId:
        description: 学时相关申请(若不存在申请环节，则为0)
        type: integer
  CreditHourApplication:
    description: 由学生发起的学时认证申请
    properties:
      value: 
        description: 所申请的学时值（按分钟记）
        type: number
      applicantId: 
        description: 申请人ID
        type: integer
      applicaitonDescription:
        description: 申请内容详述
        type: string
      status: 
        description: 申请结果状态
        type: string
      entryId: 
        description: 关联的学时授予记录（在审核批准前为0）
        type: array
        items: 
          type: integer
          
paths:
  /login:
    get:
      summary: 获取当前Token信息
      tags: 
        - Authentication
      responses:
        '200':
          description: 获取当前Token信息成功
          schema:
            $ref: '#/definitions/TokenStatus'
        '401':
          description: 无法获取当前Token信息
          headers:
            WWW_Authenticate:
              type: string
    post:
      summary: 尝试登陆
      tags: 
        - Authentication
      parameters:
        - in: body
          name: login
          required: true
          schema:
            $ref: '#/definitions/LoginRequest'
      responses:
        '200':
          description: 登陆成功
          schema:
              $ref: '#/definitions/TokenStatus'
        '401':
          $ref: "#/responses/UnauthorizedError"
  /learner:
    head:
      summary: 返回所有Learner的关键信息
      tags: 
        - Learner
      responses:
        '200':
          description: 成功
          schema:
              type: object
              properties:
                id:
                  type: integer
                  example: 1
                name:
                  type: string
                  example: John Appleseed
        '401':
          $ref: "#/responses/UnauthorizedError"
    get:
      summary: 返回所有的Leaner详细信息
      tags: 
        - Learner
      description: 返回所有的Leaner详细信息
      responses:
        '200':
          description: A JSON array of user names
          schema:
              $ref: '#/definitions/Learner'
        '401':
          $ref: "#/responses/UnauthorizedError"
    post:
      summary: 创建一个Learner
      tags: 
        - Learner
      parameters:
        - in: body
          name: login
          required: true
          schema:
              $ref: '#/definitions/Learner'
      responses:
        '201':
          description: 创建成功
          schema:
            description: 成功创建的Learner的ID
            type: object
            properties:
              id:
                type: integer
        '401':
          $ref: "#/responses/UnauthorizedError"  
  '/learner/{learnerId}':
    get:
      summary: 返回一个Learner的详细信息
      tags: 
        - Learner
      parameters:
        - in: path
          name: learnerId
          required: true
          type: integer
          format: int64
          minimum: 1
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Learner'
        '401':
          $ref: "#/responses/UnauthorizedError"
  '/learner/{learnerId}/project':
    get:
      summary: 返回一个Learner相关的课程
      tags:
        - Learner
        - Projects
      parameters:
        - in: path
          name: learnerId
          required: true
          type: integer
          format: int64
          minimum: 1
      responses:
        '200':
          description: OK
          schema:
            type: array
            items: 
              $ref: '#/definitions/Project'
  '/learner/{learnerId}/creditHour':
    get:
      summary: 返回一个Learner相关的学时记录
      tags:
        - Learner
        - CreditHour
      parameters:
        - in: path
          name: learnerId
          required: true
          type: integer
          format: int64
          minimum: 1
      responses:
        '200':
          description: OK
          schema:
            type: array
            items: 
              $ref: '#/definitions/CreditHourEntry'
responses:
  UnauthorizedError:
    description: API key is missing or invalid
    headers:
      WWW_Authenticate:
        type: string
            
